# Use the .NET Core SDK as a build image
FROM mcr.microsoft.com/dotnet/aspnet:8.0 AS base
USER app
WORKDIR /source
EXPOSE 8080
EXPOSE 8081

FROM mcr.microsoft.com/dotnet/sdk:8.0 AS build
ARG BUILD_CONFIGURATION=Release
WORKDIR /src
COPY "dotnet.csproj" "dotnet/"
RUN dotnet restore "./dotnet/dotnet.csproj"
COPY . "./dotnet/"
WORKDIR "/src/dotnet"
RUN dotnet build  -c $BUILD_CONFIGURATION -o /app/build

# Publish the application
FROM build  AS publish
ARG BUILD_CONFIGURATION=Release
RUN dotnet publish  -c Release -o /app/publish /p:UseAppHost=false

# final stage/image
FROM base AS final
WORKDIR /app
COPY --from=publish /app/publish .

# Expose the desired ports
EXPOSE 8080
EXPOSE 8081

# Define the entry point for the application
ENTRYPOINT ["dotnet", "dotnet.dll"]
