# ASP.NET Core
# Build and test ASP.NET Core projects targeting .NET Core.
# Add steps that run tests, create a NuGet package, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger: none
#- master

pr:
#- master
#- dev
#  branches:
#    include:
#    - features/*
#    exclude:
#    - features/experimental/*
  paths:
    include:
     - ServerSide/*
    exclude:
    - README.md



pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dir "ServerSide/*.sln" -Recurse | %{dotnet build --configuration $(buildConfiguration) $PSItem.FullName}'
    failOnStderr: true
    showWarnings: true
    pwsh: true
  displayName: 'dotnet build $(buildConfiguration)' 
#- script: dotnet build --configuration $(buildConfiguration)
# displayName: 'dotnet build $(buildConfiguration)'
