trigger: none

pr:
  paths:
    include:
    - '*'
    exclude:
    - README.md
pool:
  vmImage: ubuntu-latest

variables:
  buildConfiguration: 'Release'
  solution: 'TeamIdentityProvider.sln'
  buildPlatform: 'Any CPU'

steps:
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: 'dir "TeamIdentityProvider.sln" -Recurse | %{dotnet build --configuration $(buildConfiguration) $PSItem.FullName}'
    failOnStderr: true
    showWarnings: true
    pwsh: true
  displayName: 'dotnet build $(buildConfiguration)'
